<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'description' => 'The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.',
                'price' => 1199.99,
                'stock_quantity' => 50,
                'brand' => 'Apple',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Premium Android smartphone with S Pen, 200MP camera, and stunning AMOLED display.',
                'price' => 1299.99,
                'stock_quantity' => 45,
                'brand' => 'Samsung',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'Google\'s flagship phone with amazing AI features and best-in-class camera.',
                'price' => 999.99,
                'stock_quantity' => 60,
                'brand' => 'Google',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'description' => 'Flagship killer with Snapdragon 8 Gen 3, 100W fast charging, and smooth 120Hz display.',
                'price' => 799.99,
                'stock_quantity' => 40,
                'brand' => 'OnePlus',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'MacBook Pro 16" M3 Max',
                'slug' => 'macbook-pro-16-m3-max',
                'description' => 'Professional-grade laptop with M3 Max chip, stunning Retina display, and all-day battery life.',
                'price' => 3499.99,
                'stock_quantity' => 25,
                'brand' => 'Apple',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'description' => 'Premium Windows laptop with 13th Gen Intel Core i9, NVIDIA GeForce RTX 4070, and InfinityEdge display.',
                'price' => 2499.99,
                'stock_quantity' => 30,
                'brand' => 'Dell',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'slug' => 'lenovo-thinkpad-x1-carbon',
                'description' => 'Business ultrabook with legendary ThinkPad keyboard, military-grade durability, and long battery life.',
                'price' => 1899.99,
                'stock_quantity' => 35,
                'brand' => 'Lenovo',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'HP Spectre x360',
                'slug' => 'hp-spectre-x360',
                'description' => '2-in-1 convertible laptop with stunning design, Intel Evo platform, and touchscreen.',
                'price' => 1699.99,
                'stock_quantity' => 28,
                'brand' => 'HP',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'ASUS ROG Strix Gaming Desktop',
                'slug' => 'asus-rog-strix-gaming-desktop',
                'description' => 'High-performance gaming PC with RTX 4090, AMD Ryzen 9 7950X, and liquid cooling.',
                'price' => 3999.99,
                'stock_quantity' => 15,
                'brand' => 'ASUS',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Panasonic Cordless Phone System',
                'slug' => 'panasonic-cordless-phone-system',
                'description' => 'DECT 6.0 cordless phone with answering machine, caller ID, and expandable handsets.',
                'price' => 89.99,
                'stock_quantity' => 100,
                'brand' => 'Panasonic',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'AT&T Corded Landline Phone',
                'slug' => 'att-corded-landline-phone',
                'description' => 'Traditional corded telephone with large buttons, caller ID display, and speakerphone.',
                'price' => 29.99,
                'stock_quantity' => 150,
                'brand' => 'AT&T',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'VTech DECT 6.0 Cordless Phone',
                'slug' => 'vtech-dect-60-cordless-phone',
                'description' => 'Expandable cordless phone system with digital answering system and call blocking.',
                'price' => 59.99,
                'stock_quantity' => 80,
                'brand' => 'VTech',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Anker PowerCore 20000mAh Power Bank',
                'slug' => 'anker-powercore-20000mah',
                'description' => 'High-capacity portable charger with dual USB ports and fast charging technology.',
                'price' => 49.99,
                'stock_quantity' => 200,
                'brand' => 'Anker',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Apple AirPods Pro (2nd Gen)',
                'slug' => 'apple-airpods-pro-2nd-gen',
                'description' => 'Premium wireless earbuds with active noise cancellation, transparency mode, and spatial audio.',
                'price' => 249.99,
                'stock_quantity' => 120,
                'brand' => 'Apple',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Logitech MX Master 3S Wireless Mouse',
                'slug' => 'logitech-mx-master-3s',
                'description' => 'Ergonomic wireless mouse with ultra-fast scrolling, customizable buttons, and multi-device pairing.',
                'price' => 99.99,
                'stock_quantity' => 90,
                'brand' => 'Logitech',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Samsung 65W USB-C Fast Charger',
                'slug' => 'samsung-65w-usb-c-charger',
                'description' => 'High-speed wall charger with USB-C PD and PPS technology for laptops and phones.',
                'price' => 59.99,
                'stock_quantity' => 150,
                'brand' => 'Samsung',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Spigen Tough Armor Case (Universal)',
                'slug' => 'spigen-tough-armor-case',
                'description' => 'Military-grade protection case with dual-layer design and kickstand.',
                'price' => 34.99,
                'stock_quantity' => 180,
                'brand' => 'Spigen',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Sony WH-1000XM5 Headphones',
                'slug' => 'sony-wh-1000xm5-headphones',
                'description' => 'Industry-leading noise canceling headphones with exceptional sound quality and 30-hour battery.',
                'price' => 399.99,
                'stock_quantity' => 70,
                'brand' => 'Sony',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}
